/*  KIARA - Middleware for efficient and QoS/Security-aware invocation of services and exchange of messages
 *
 *  Copyright (C) 2013  German Research Center for Artificial Intelligence (DFKI)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#ifndef KIARA_PP_0A0ZNAOU2TTQRV0FVWC5_H
#define KIARA_PP_0A0ZNAOU2TTQRV0FVWC5_H

#include <KIARA/kiara.h>
#include <KIARA/kiara_macros.h>

/* This file was generated by kiara-preprocessor tool */

#include "aostest_types.h"

KIARA_DECL_STRUCT(Vec3f,
  KIARA_STRUCT_MEMBER(KIARA_FLOAT, x)
  KIARA_STRUCT_MEMBER(KIARA_FLOAT, y)
  KIARA_STRUCT_MEMBER(KIARA_FLOAT, z)
)
KIARA_DECL_STRUCT(Quatf,
  KIARA_STRUCT_MEMBER(KIARA_FLOAT, r)
  KIARA_STRUCT_MEMBER(Vec3f, v)
)
KIARA_DECL_STRUCT(Location,
  KIARA_STRUCT_MEMBER(Vec3f, position)
  KIARA_STRUCT_MEMBER(Quatf, rotation)
)
KIARA_DECL_PTR(Location_ptr, Location)
KIARA_DECL_STRUCT(LocationList,
  KIARA_STRUCT_ARRAY_MEMBER(Location_ptr, locations, KIARA_INT, num_locations)
)
KIARA_DECL_CONST_PTR(const_LocationList_ptr, LocationList)
KIARA_DECL_FUNC(AOSTest_SetLocations,
  KIARA_FUNC_ARG(const_LocationList_ptr, locations)
)
KIARA_DECL_PTR(LocationList_ptr, LocationList)
KIARA_DECL_FUNC(AOSTest_GetLocations,
  KIARA_FUNC_RESULT(LocationList_ptr, locations)
)

#endif
